### ISSUE TITLE
Make QuestionsForm Component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#10]

**Comment by saumyanasa** [comment]
Di, assign this to Khushi and me

**Comment by Manvityagi** [comment]
> Di, assign this to Khushi and me

Ask Khushi to comment, will assign her 
Assigned to you

**Comment by vaishali614** [comment]
Please assign me this issue.

**Comment by Manvityagi** [comment]
> Please assign me this issue.

Assigned
