### ISSUE TITLE
Make Navbar Component

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#12]

**Comment by divanshurox** [comment]
Hi, I am a beginner in open source, can I work on this? Thank you.

**Comment by Manvityagi** [comment]
@divanshurox Assigned to you, 
https://xd.adobe.com/view/7b3e5159-7351-45ee-7a8d-17c7033ecb00-0d0f/?fullscreen
You can find the design here, you have to design the Navbar according to this design. 
Good Luck!

**Comment by divanshurox** [comment]
I am new to this, Do I need to follow the exact dimensions given in the link above?

It should be responsive, bootstrap is included already in the root of project. Color Scheme and Font should be same as in design.
