### ISSUE TITLE
Couple of changes for a better UI

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#140]
![image](https://user-images.githubusercontent.com/32908093/104897852-e49aff00-599e-11eb-885c-c88fcf8bbb14.png)

2. Make the part in green cleaner

**Comment by sakshi300699** [comment]
In point 1, is it required to change the colour of the background of navbar? @Manvityagi

**Comment by Manvityagi** [comment]
> In point 1, is it required to change the colour of the background of navbar? @Manvityagi

Yes for smaller screens.

**Comment by capblack222** [comment]
If it is not yet fixed, Can I work on this? @Manvityagi

**Comment by Manvityagi** [comment]
> If it is not yet fixed, Can I work on this? @Manvityagi

Yes, that would be great. Go ahead @capblack222

**Comment by Manvityagi** [comment]
> > If it is not yet fixed, Can I work on this? @Manvityagi
> 
> Yes, that would be great. Go ahead @capblack222

Any updates @capblack222

**Comment by d2Anubis** [comment]
Hi, Can I work on this? I have tried changing the css of some components to make the site look better on small website.
![image](https://user-images.githubusercontent.com/59616618/118599592-6a07b200-b7cd-11eb-9c21-358573ee1251.png)
Let me know if I can proceed.

**Comment by Manvityagi** [comment]
> Hi, Can I work on this? I have tried changing the css of some components to make the site look better on small website.
> ![image](https://user-images.githubusercontent.com/59616618/118599592-6a07b200-b7cd-11eb-9c21-358573ee1251.png)
> Let me know if I can proceed.

CC: @DeepanshiD @vaishali614 Wanna take a look at this one? 
I think the header can be left of the same color as before, the contents can be given a light bg.
