### ISSUE TITLE
centralized buttons in mobile view

### ISSUE THREAD

**Issue by Abhijay007** [Girl-Code-It/Girl-Code-It-Website#144]
Currently, in the mobile view or smaller screens, most of the buttons are not centralized or you can say not align properly which sets a bad UI experience.

***Screenshots***

Screenshot 1          |  Screenshot 2           | Screenshot 3        
:-------------------------:|:-------------------------:|:-------------------------:
![3-gci](https://user-images.githubusercontent.com/64387054/106644238-da891b00-65b0-11eb-90c9-ce90c65645cf.PNG)|![1-gci](https://user-images.githubusercontent.com/64387054/106644022-8ed67180-65b0-11eb-92c4-3b18888e7788.PNG)|![2-gci](https://user-images.githubusercontent.com/64387054/106643876-533ba780-65b0-11eb-8cc3-9d8621c19946.PNG)

In the above screenshots, as you can see the buttons are slightly aligned left or right but not centered.

**Comment by Manvityagi** [comment]
Right @Abhijay007. The buttons produce a bad UI experience on smaller screens. You can take this up if you want to.

**Comment by Abhijay007** [comment]
> Right @Abhijay007. The buttons produce a bad UI experience on smaller screens. You can take this up if you want to.

ok @Manvityagi  ma'am I will open a PR for this.
