### ISSUE TITLE
Alignment of Banner section Buttons in the desktop view

### ISSUE THREAD

**Issue by Abhijay007** [Girl-Code-It/Girl-Code-It-Website#145]
Currently, the two buttons in the banner section of the website "About us" and "volunteer" seem to be not aligned properly 

***Screenshot***

![banner-buttons](https://user-images.githubusercontent.com/64387054/106717914-55404d80-6626-11eb-8f0a-62b8d4a6468a.jpg)

I think it looks good if we align them next to each other instead of that overlapping thing

![banner section](https://user-images.githubusercontent.com/64387054/106718146-a4867e00-6626-11eb-8d79-82e2f795ec20.gif)

***changes I made***

I removed that hover effect from each of these buttons and align them next to each other, rest of the buttons are as it is.

**Comment by Manvityagi** [comment]
@Abhijay007  We knowingly had the buttons staggered as per the original design.

CC: @vaishali614 @abdus
