### ISSUE TITLE
Changes in UI so that CODEMAPS are easily accessible 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#149]
Many people have not been able to access our [codemaps](https://girlcodeit.com/codemaps) even after landing on the website. 
This is a big issue as Codemaps is the primary feature and uniqueness of Girl Code It. 

Suggest changes in UI so that anyone who visits the homepage can easily know about codemaps and use them.

**Comment by Sukriti-sood** [comment]
## Suggestion:-
- Currently Size of Impact Section is comparatively less We can increase some height .
- Can increase some height of Impact Cards and and Can Add Hover Effects.

**Comment by akshay1027** [comment]
I think "what do we do" should come before "about us", this will instantly grab the attention of users! "About us" can be moved after "what do we do". @Manvityagi . Also I will try to make the cards more attractive

**Comment by Manvityagi** [comment]
> ## Suggestion:-
> * Currently Size of Impact Section is comparatively less We can increase some height .
> * Can increase some height of Impact Cards and and Can Add Hover Effects.

Those are good suggestions @Sukriti-sood. 
You have another issue assigned, Please work on that first, then you can come here again.

**Comment by Manvityagi** [comment]
> I think "what do we do" should come before "about us", this will instantly grab the attention of users! "About us" can be moved after "what do we do". @Manvityagi . Also I will try to make the cards more attractive

Hmm, Sounds good to me. Give it a try @akshay1027

**Comment by Manvityagi** [comment]
@akshay1027  Can you work on this as a priority? 
I am tired of people texting and telling me Codemaps are not `eye-catching`.

**Comment by akshay1027** [comment]
Sure then!
