### ISSUE TITLE
Fix the Navbar

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#150]
On clicking the titles in navbar, the screen covers the main title, which doesn't look good. Ideally, the title should also be a part of the new screen. 

Current Behavior: 
![Issue](https://media.giphy.com/media/VlqLiT589MBGxeF7N5/giphy.gif) 

Expected Behavior: 
![Correct](https://media.giphy.com/media/tdqSFo7VHHvnONMJFL/giphy.gif)

**Comment by Sukriti-sood** [comment]
@Manvityagi I want to work on this.

**Comment by Manvityagi** [comment]
Go ahead @Sukriti-sood
