### ISSUE TITLE
is this repo is only for girls?

### ISSUE THREAD

**Issue by vivek80801** [Girl-Code-It/Girl-Code-It-Website#160]
I want to contribute to this repo. But I think this repo is only for girl coders. Because name of this repo is `Girl-Code-It-Website-Frontend`. But I can see many contributor of this project is boy. So, I am asking this question. is this repo is only for girls?

If I violates any `code of conduct` or `law`. Please for give me. I am beginner.

Thanks for your time.

**Comment by praveenscience** [comment]
Yes, you did violate something by not even reading the readme or website on the same page.

People are so quick to judge. Had you read it in the first page:

> **Is it only for girls?**
>
> No! Although the name suggests that, but Girl Code It welcomes everyone in need of guidance irrespective of their gender.

**Comment by vivek80801** [comment]
Hello sir,

I read the readme.

> Girl Code It aka GCI, is a group of people who firmly believe in this statement and are eager to build a healthy coding culture among young coders. smiley In a world teeming with possibilities due to the rapid growth of technology everywhere, let's not get left behind in the rush! GCI is here to help you navigate your way through the amazing world of computers and coding. heart_eyes
So what are you waiting for? Come join us! blush sparkles

1. I do not know what is meaning of *people* here. I thought *people* could be women only. As I said I am beginner .
2. I am not judging anyone. I can not judge anyone. I don't have enough time to judge anyone. If any program supports girl coders. That is a good thing. Because I think our **sisters** need support. I also want to support that program if I can.
3. I am closing this issue as I get my answer.

Things are confusing at least for me. Sorry, If I heart anyone. It will great if we clarify things in readme.
