### ISSUE TITLE
Add smooth transition in meettheteam cards on hover

### ISSUE THREAD

**Issue by supzi-del** [Girl-Code-It/Girl-Code-It-Website#163]
- [x] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Expected Behavior:
Smooth css hover effect

# Current Behavior:

What is the current behavior?
On this page 👉 https://girlcodeit.com/meettheteam  when each card is hovered upon, the transition is a bit harsh/rough. 

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
A CSS code [transition: all 0.5s] can be added in order to have a smoother hover effect.

**Comment by vaishali614** [comment]
@supzi-del Thanks for reporting the issue. Please go ahead.

**Comment by Manvityagi** [comment]
Yeah, Little things can affect the experience. Nice Observation @supzi-del
