### ISSUE TITLE
Make ImpactCard and Impact component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#17]

**Comment by SinghVikram97** [comment]
Change the name also to ImpactCard instead of ImpaceList whoever will work on this issue

**Comment by Meghag5** [comment]
I will work on this task

**Comment by Manvityagi** [comment]
> I will work on this task

Change the name also to ImpactCard instead of ImpaceList  @Meghag5 

Assigned to you
