### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#178]
1. This FAQ
What Codemaps do we offer?
Change the content to 
```We offer Data Structures and Algorithms CodeMap in 3 languages - C++, Python, and Java and two development codemaps i.e. Frontend Web Development and ReactJS for beginners. Check all of them here - https://girlcodeit.com/codemaps```

2. Add question - 
Q - Are the courses/codemaps paid? 
A - No, GCI operates as a nonprofit community, hence everything is free of cost.

3. Add Question - 
Q - How to enroll in a course/codemap?
A - The courses are open to all and separate enrollment is not required. You can just head on to what you want to learn and start learning.  All courses/codemaps here - https://girlcodeit.com/codemaps

**Comment by naveen8801** [comment]
Hey @Manvityagi  , I'd like to contribute in this project , can i start with this issue please  :))

**Comment by Manvityagi** [comment]
> Hey @Manvityagi , I'd like to contribute in this project , can i start with this issue please :))

Sure Naveen, Go ahead.
