### ISSUE TITLE
Add Discord Server Link on Home Page and on all Codemaps

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#188]

**Comment by paarth17032000** [comment]
Hey! can i work on this and can you please give me a brief description on how to proceed

**Comment by Manvityagi** [comment]
> Hey! can i work on this and can you please give me a brief description on how to proceed

Sure, Go ahead

**Comment by paarth17032000** [comment]
Okay so where to put the link and do we have to put it in icon also can you please provide me with the link

**Comment by Manvityagi** [comment]
> Okay so where to put the link and do we have to put it in icon also can you please provide me with the link

This is the discord link: https://discordgci.netlify.app
On Home Page, Put it with the icons on left on the top.

**Comment by Manvityagi** [comment]
On each of these Codemaps: https://girlcodeit.com/onecodemap?id=cpp.json

I think, we can have a button alongside.. Submit solutions with text `Discuss Doubts here` 


CC: @vaishali614
