### ISSUE TITLE
Correct the Github Link in Social Media Sidebar

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#194]
The sidebar is having wrong link for github, 
The correct link is this - 
https://github.com/Girl-Code-It

**Comment by maahiunnati** [comment]
Mam ,i want to solve this issue,but when i am opening it in browser in my local system its a blank page.Can you help me out Please.

**Comment by AshAman999** [comment]
@Manvityagi  
Mam can you review the pull request, I fixed the issue, had to just do a single line edit
