### ISSUE TITLE
Change Structure of components  

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#46]
Change the structure of components, add all the current components and call it homepage, 
Make 3 new folders, 
-> codemap_details
-> oppc_details
-> one_codemap 

Make sure all the imports are correct after making the changes.

**Comment by Manvityagi** [comment]
@divanshurox

**Comment by harsha14gupta** [comment]
I'll work on this.

**Comment by Manvityagi** [comment]
@harsha14gupta Assigned to you
