### ISSUE TITLE
Add more cards to impact section 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#47]
This is the impact section on homepage currently having 2 cards, 
![image](https://user-images.githubusercontent.com/32908093/89614630-748e3600-d8a2-11ea-8208-8bc5f34f4134.png)

You need to add 4 more cards to it, of similar dimensions, 
1. Open-Source Journey (Get your journey in open-source started with our open-source projects)
2. Daily Leetcoding (Solve Leetcode challenges every day with our coders) 
3. Get Career guidance (Confused about your interest/career in tech, Get Personal guidance from experts) 
4. Build good Linkedin Profile (Learn how to make an impressive profile) 

The issue is tagged medium because you yourself need to figure out the illustrations(images) for each card.

**Comment by Meghag5** [comment]
i will work on this

**Comment by Manvityagi** [comment]
Assigned to you @Meghag5
