### ISSUE TITLE
Create codemap_details/CodeMapBanner component  

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#53]
Find the CodeMapBanner.js file in src/codemap_details/Components and write your code in it. 
Find the CodeMapBanner.modulecss file in src/codemap_details/CSS and write the corresponding CSS there. 

Guidelines: 
1. Use react-bootstrap 
2. The component should be responsive with all screen sizes. 
3. Don't use element selector in CSS, use classes instead. 

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/1b92180c-29d0-436d-b2f7-175dd976fa45/

![image](https://user-images.githubusercontent.com/32908093/89916158-ece35700-dc14-11ea-9bef-7a1562ca418c.png)
This is the Banner Component. 

Some Extra Work - Change the name of this component from CodeMapBanner to Banner, and change the name of the JS and CSS files of this component in the same way, and don't forget to change the corresponding imports everywhere.

**Comment by harsha14gupta** [comment]
I'll work on this.

**Comment by Manvityagi** [comment]
Assigned to you @harsha14gupta
