### ISSUE TITLE
Create oppc_details/KnowAbout and oppc_details/KnowAboutCard.js components

### ISSUE THREAD

**Issue by SinghVikram97** [Girl-Code-It/Girl-Code-It-Website#54]
Find the KnowAbout.js file in src/oppc_details/Components and write your code in it. 
Find the KnowAboutCard.js file in src/oppc_details/Components and write code for KnowAbout card in it.
Find the KnowAbout.module.css file in src/oppc_details/CSS and write the corresponding CSS there. 

Guidelines: 
1. Use react-bootstrap 
2. The component should be responsive to all screen sizes. 
3. Don't use element selector in CSS use classes instead.

Refer Design here: https://xd.adobe.com/view/6e690bcb-76dd-4cfd-58c0-d7daeaa39a0c-1858/
![image](https://user-images.githubusercontent.com/18444000/89917437-6cbdf100-dc16-11ea-8246-883ffbe3058b.png)

**Comment by khushib12** [comment]
I will work on this issue
