### ISSUE TITLE
Create codemap_details/CodeMapCard component and CodeMap component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#55]
Find the CodeMapCard.js and CodeMap.js file in src/codemap_details/Components and write your code in it.
Find the CodeMapCard.module.css and CodeMap.module.css file in src/codemap_details/CSS and write the corresponding CSS there.

Guidelines:
1. Use react-bootstrap
2. The component should be responsive with all screen sizes.
3. Don't use element selector in CSS, use classes instead.

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/1b92180c-29d0-436d-b2f7-175dd976fa45/

![Codemap Component](https://user-images.githubusercontent.com/32908093/89917258-354f4480-dc16-11ea-89ae-184eba9d41e6.png)

**Comment by Kritimukhija** [comment]
I'll work on this.

**Comment by Manvityagi** [comment]
Assigned @Kritimukhija

**Comment by happycoder0011** [comment]
is it done?? Can i work on it?

**Comment by Manvityagi** [comment]
> is it done?? Can i work on it?

Yes it's under review, 
We are actually not opening new issues at this point of time. You may revisit after sometime. 

You may have a look here if you are looking for some contributions https://github.com/Manvityagi/Data-Structures-and-Algorithms  @happycoder0011

**Comment by happycoder0011** [comment]
thanks.
