### ISSUE TITLE
Create codemap_details/Query component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#56]
Find the Query.js file in src/codemap_details/Components and write your code in it.
Find the Query.module.css file in src/codemap_details/CSS and write the corresponding CSS there.

Guidelines:
1. Use react-bootstrap
2. The component should be responsive with all screen sizes.
3. Don't use element selector in CSS, use classes instead.

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/1b92180c-29d0-436d-b2f7-175dd976fa45/

![Query Component](https://user-images.githubusercontent.com/32908093/89917758-d0481e80-dc16-11ea-897b-06e9ce3134ea.png)

**Comment by prachibansal2000** [comment]
i will work on this

**Comment by Manvityagi** [comment]
Assigned to you @prachibansal2000
