### ISSUE TITLE
Create oppc_details/OppCalenderBanner component

### ISSUE THREAD

**Issue by SinghVikram97** [Girl-Code-It/Girl-Code-It-Website#57]
Find the OppCalenderBanner.js file in src/oppc_details/Components and write your code in it.
Find the OppCalenderBanner.module.css file in src/oppc_details/CSS and write the corresponding CSS there.

Guidelines:

1. Use react-bootstrap
2. The component should be responsive to all screen sizes.
3. Don't use element selector in CSS use classes instead.

Refer Design here: https://xd.adobe.com/view/6e690bcb-76dd-4cfd-58c0-d7daeaa39a0c-1858/
![image](https://user-images.githubusercontent.com/18444000/89917851-f1107400-dc16-11ea-83f6-f2ba554767a4.png)

**Comment by srishtij2000** [comment]
I'll work on this issue

**Comment by Manvityagi** [comment]
@srishtij2000 You Kashika first need to send the PR for footer and have it merged, the only you will be assigned a new issue,

**Comment by srishtij2000** [comment]
Okay okay
