### ISSUE TITLE
Create codemap_details/WhatToPay component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#58]
Find the WhatToPay.js file in src/codemap_details/Components and write your code in it.
Find the WhatToPay.module.css file in src/codemap_details/CSS and write the corresponding CSS there.

Guidelines:
1. Use react-bootstrap
2. The component should be responsive with all screen sizes.
3. Don't use element selector in CSS, use classes instead.

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/1b92180c-29d0-436d-b2f7-175dd976fa45/

![WhatToPay Component](https://user-images.githubusercontent.com/32908093/89917970-169d7d80-dc17-11ea-84ee-a623bee00432.png)

**Comment by MiliJolly** [comment]
I will work on this

**Comment by Manvityagi** [comment]
Assigned @MiliJolly
