### ISSUE TITLE
Create codemap_details/WhyCodeMap component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#59]
Find the WhyCodeMap.js file in src/codemap_details/Components and write your code in it.
Find the WhyCodeMap.module.css file in src/codemap_details/CSS and write the corresponding CSS there.

Guidelines:
1. Use react-bootstrap
2. The component should be responsive with all screen sizes.
3. Don't use element selector in CSS, use classes instead.

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/1b92180c-29d0-436d-b2f7-175dd976fa45/

![WhyCodeMap Component](https://user-images.githubusercontent.com/32908093/89918247-6a0fcb80-dc17-11ea-808e-eb2a570a368b.png)
]()

**Comment by Meghag5** [comment]
I will work on this

**Comment by Manvityagi** [comment]
Assigned @Meghag5
