### ISSUE TITLE
Create one_codemap/OneCodeMap component 

### ISSUE THREAD

**Issue by SinghVikram97** [Girl-Code-It/Girl-Code-It-Website#60]
Find the OneCodeMap.js file in src/one_codemap/Components and write your code in it.
Find the OneCodeMap.module.css file in src/one_codemap/CSS and write the corresponding CSS there.

Guidelines:

1. Use react-bootstrap
2. The component should be responsive to all screen sizes.
3. Don't use element selector in CSS use classes instead.

Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/fb80e0ed-0c79-492c-a7f1-b234216243e0/

![image](https://user-images.githubusercontent.com/18444000/89918824-249fce00-dc18-11ea-8305-e6df6a4d9228.png)

**Comment by divanshurox** [comment]
I will work on this.

**Comment by Manvityagi** [comment]
Assigned @divanshurox
