### ISSUE TITLE
Make a new route for CodeMapDetails Page 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#61]
Make a new route with path `/codemaps/:course_id` which will link to the one_codeMap Detail Page. 

This is the codeMapDetail Page. 
https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/fb80e0ed-0c79-492c-a7f1-b234216243e0/

And associated components are present in src/one_codemap folder. 

Hint: Refer the App.js file

**Comment by happycoder0011** [comment]
hey can i do this? I am learning reactjs
