### ISSUE TITLE
Create one_codemap/CodeMapMilestone component

### ISSUE THREAD

**Issue by SinghVikram97** [Girl-Code-It/Girl-Code-It-Website#62]
Find theCodeMapMilestone.js file in src/one_codemap/Components and write your code in it.
Find the CodeMapMilestone.module.css file in src/one_codemap/CSS and write the corresponding CSS there.

Guidelines:

1. Use react-bootstrap
2. The component should be responsive to all screen sizes.
3. Don't use element selector in CSS use classes instead.
Refer Design here: https://xd.adobe.com/view/1cf18476-27a4-4007-5fc7-0154fbe60af6-6ac0/screen/fb80e0ed-0c79-492c-a7f1-b234216243e0/

![image](https://user-images.githubusercontent.com/18444000/89919175-911acd00-dc18-11ea-94fd-4543073d1de4.png)

**Comment by JanviMahajan14** [comment]
Hi, @SinghVikram97 I would like to work on this! Can you tell me how we can create these highlighted bullet points before the C++?

**Comment by SinghVikram97** [comment]
@JanviMahajan14 Check this out https://codepen.io/VikramSB/pen/qBZbqqa

**Comment by Manvityagi** [comment]
> Hi, @SinghVikram97 I would like to work on this! Can you tell me how we can create these highlighted bullet points before the C++?

Hi @JanviMahajan14! As you are a new contributor, please drop an email to girlcodeit@gmail.com to be added to the communication channel, mentioning the same in your email.

**Comment by Le-Roi777** [comment]
Hey guys : )
I would like to give this a go...can i grab it?
