### ISSUE TITLE
Make CodeMapCard and CodeMap Component 

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#8]
Make both CodeMap.js and CodeMapCard.js

**Comment by Kritimukhija** [comment]
I'll work on this issue

**Comment by Manvityagi** [comment]
@Kritimukhija Assigned

**Comment by srishtij2000** [comment]
I am also working on this issue

**Comment by Manvityagi** [comment]
> I am also working on this issue

@Assigned to you as well @srishtij2000
