### ISSUE TITLE
Same issue in java for beginners

### ISSUE THREAD

**Issue by Manvityagi** [Girl-Code-It/Girl-Code-It-Website#97]
![image](https://user-images.githubusercontent.com/32908093/104629929-28041d80-56c0-11eb-9db8-086207187ed1.png)

**Comment by Heikrana** [comment]
Because, there's no java.json file in milestones folder.
Just a suggestion, Issues should be more descriptive. I spent the last 10 minutes analysing the code just to find out that there's no file for fetching.
